### PR TITLE
Zivid and vtk visualizer

### PR DESCRIPTION
**Pull request by SatjaSivcev**
Can you please review the code of this sample program? I will make a mini-tutorial on how to install and run the vtk visualizer for this sample on the knowledge base.

### CODE REVIEW

**Comment by nedrebo** [comment]
This PR looks like it includes lots of the changes from #6. I would make this a PR draft or not make the PR at all until #6 is merged. Else we risk that people waste time reviewing the same changes twice, or if they notice it like I did, then they will have a hard time untangling what changes to review.

**Comment by SatjaSivcev** [comment]
> 
> 
> This PR looks like it includes lots of the changes from #6. I would make this a PR draft or not make the PR at all until #6 is merged. Else we risk that people waste time reviewing the same changes twice, or if they notice it like I did, then they will have a hard time untangling what changes to review.

**Comment by SatjaSivcev** [comment]
I've noticed that @nedrebo but I didn't know how to deal with it.

**Comment by nedrebo** [comment]
> I've noticed that @nedrebo but I didn't know how to deal with it.

I think that when you created this branch you should have branched from master and not from the branch in #6.

**Pull request closed without merging**
