### PR TITLE
Black formatting with line-length 119(120)

### PR DESCRIPTION
**Pull request by torbsorb**
We lint for line length 120, so we configure Black to match. Instead of the default 88.

### CODE REVIEW

**Comment by SatjaSivcev** [comment]
@eskaur can you review this PR, please?

**Comment by eskaur** [comment]
This commit breaks the CI, so can't approve at this point. Are you sure the CI picks up the new black settings in pyproject.toml? @SatjaSivcev

**Comment by SatjaSivcev** [comment]
> 
> 
> This commit breaks the CI, so can't approve at this point. Are you sure the CI picks up the new black settings in pyproject.toml? @SatjaSivcev

_By default Black looks for pyproject.toml starting from the common base directory of all files and directories passed on the command line. If it’s not there, it looks in parent directories. It stops looking when it finds the file, or a .git directory, or a .hg directory, or the root of the file system, whichever comes first.

If you’re formatting standard input, Black will look for configuration starting from the current working directory.

You can also explicitly specify the path to a particular file that you want with --config. In this situation Black will not look for any other file._

I could try with --config? I don't know how to confirm if it did find it or not.

**Comment by SatjaSivcev** [comment]
> 
> 
> > This commit breaks the CI, so can't approve at this point. Are you sure the CI picks up the new black settings in pyproject.toml? @SatjaSivcev
> 
> _By default Black looks for pyproject.toml starting from the common base directory of all files and directories passed on the command line. If it’s not there, it looks in parent directories. It stops looking when it finds the file, or a .git directory, or a .hg directory, or the root of the file system, whichever comes first.
> 
> If you’re formatting standard input, Black will look for configuration starting from the current working directory.
> 
> You can also explicitly specify the path to a particular file that you want with --config. In this situation Black will not look for any other file._
> 
> I could try with --config? I don't know how to confirm if it did find it or not.

@eskaur I tried figuring this on my own but I am struggling. Can you help me figure out what is going wrong?

**Comment by eskaur** [comment]
Turns out this had nothing to do with failing to find pyproject.toml, but rather it's an issue with different versions of black having different requirements. Which version of "black" are you running locally?

What I am seeing is that the files look fine to e.g. `black- 19.10b0` but they look wrong to `black-20.8b1`. The CI happens to run the latter, because it's the default in ubuntu-18.04's default-python.

**Comment by SatjaSivcev** [comment]
> black-20.8b1

Do you know how to check black version?

**Comment by eskaur** [comment]
> > black-20.8b1
> 
> Do you know how to check black version? I am using visual studio code

`black --version` in a terminal.

**Comment by SatjaSivcev** [comment]
> 
> 
> > > black-20.8b1
> > 
> > 
> > Do you know how to check black version? I am using visual studio code
> 
> `black --version` in a terminal.

Doesn't work for me...

`C:\Users\SatjaSivcev>pip install black
Requirement already satisfied: black in c:\users\satjasivcev\appdata\roaming\python\python39\site-packages (20.8b1)
Requirement already satisfied: click>=7.1.2 in c:\users\satjasivcev\appdata\roaming\python\python39\site-packages (from black) (7.1.2)
Requirement already satisfied: regex>=2020.1.8 in c:\users\satjasivcev\appdata\roaming\python\python39\site-packages (from black) (2020.10.23)
Requirement already satisfied: typed-ast>=1.4.0 in c:\users\satjasivcev\appdata\roaming\python\python39\site-packages (from black) (1.4.1)
Requirement already satisfied: toml>=0.10.1 in c:\users\satjasivcev\appdata\roaming\python\python39\site-packages (from black) (0.10.1)
Requirement already satisfied: typing-extensions>=3.7.4 in c:\users\satjasivcev\appdata\roaming\python\python39\site-packages (from black) (3.7.4.3)
Requirement already satisfied: appdirs in c:\users\satjasivcev\appdata\roaming\python\python39\site-packages (from black) (1.4.4)
Requirement already satisfied: pathspec<1,>=0.6 in c:\users\satjasivcev\appdata\roaming\python\python39\site-packages (from black) (0.8.0)
Requirement already satisfied: mypy-extensions>=0.4.3 in c:\users\satjasivcev\appdata\roaming\python\python39\site-packages (from black) (0.4.3)

C:\Users\SatjaSivcev>black --version
'black' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\SatjaSivcev>python black --version
python: can't open file 'C:\Users\SatjaSivcev\black': [Errno 2] No such file or directory

C:\Users\SatjaSivcev>python3 black --version

C:\Users\SatjaSivcev>`

**Pull request closed without merging**
