### PR TITLE
Modify read_zdf to include point cloud iteration

### PR DESCRIPTION
**Pull request by SatjaSivcev**
read_zdf.py is modified and renamed to read_iterate_zdf.py

### CODE REVIEW

**Comment by SatjaSivcev** [comment]
@chrisasc once we merge ReadIterateZDF for C++ please review this one

**Comment by chrisasc** [comment]
I merged ReadIterateZDF in C++ a minute ago, this is also (i my opinion) ready to be merged

**Comment by SatjaSivcev** [comment]
I didn't like how it displayed the text. So, another go.

**Comment by SatjaSivcev** [comment]
Reminder for next round of review

**Comment by SatjaSivcev** [comment]
@chrisasc can you do one last review?

**Pull request merged**
